let PRODUCTS = [];
function rupiah(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));}
function lynkUrl(p){return p.lynk_url || (window.CONFIG && CONFIG.lynkStoreUrl) || '#';}
function safeText(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function fromDb(p){return {...p,member_url:p.file_path||'',id:String(p.id)};}
function productCard(p){return `<article class="visual-product-card fade-in"><a class="visual-product-link" href="product-detail.html?id=${encodeURIComponent(p.id)}" aria-label="Lihat ${safeText(p.name)}"><div class="visual-product-icon">${safeText(p.icon||'📚')}</div><h3>${safeText(p.name)}</h3><span class="visual-product-category">${safeText(p.category||'Produk')}</span><span class="member-only-label">🔒 Akses member</span></a></article>`;}
function getLocalProducts(){return (window.CONFIG&&Array.isArray(CONFIG.catalogProducts))?CONFIG.catalogProducts:[];}
async function loadProducts(){if(window.sb){const {data,error}=await sb.from('products').select('*').eq('is_active',true).order('created_at',{ascending:false});if(!error&&Array.isArray(data)&&data.length){PRODUCTS=data.map(fromDb);return PRODUCTS;}}PRODUCTS=getLocalProducts();return PRODUCTS;}
async function isSignedIn(){if(!window.sb)return false;const {data,error}=await sb.auth.getUser();return !error&&!!data?.user;}
function memberViewButton(p){return `<a class="btn full" href="member-view.html?id=${encodeURIComponent(p.id)}">Lihat Produk 🔒</a>`;}
document.addEventListener('DOMContentLoaded',async()=>{
 const data=await loadProducts();const featured=document.getElementById('featured');const catalog=document.getElementById('catalog');
 if(featured){const rows=data.filter(p=>p.featured);featured.innerHTML=rows.length?rows.map(productCard).join(''):'<div class="notice">Belum ada produk.</div>';}
 if(catalog){const params=new URLSearchParams(location.search);const initial=params.get('cat');const search=document.getElementById('search');const category=document.getElementById('category');const cats=[...new Set(data.map(p=>p.category).filter(Boolean))];if(category){category.innerHTML='<option>Semua Kategori</option>'+cats.map(c=>`<option>${safeText(c)}</option>`).join('');if(initial)category.value=initial;}function render(){const q=(search?.value||'').toLowerCase();const c=category?.value||'Semua Kategori';const rows=data.filter(p=>(c==='Semua Kategori'||p.category===c)&&(!q||String(p.name).toLowerCase().includes(q)||String(p.description||'').toLowerCase().includes(q)));catalog.innerHTML=rows.length?rows.map(productCard).join(''):'<div class="notice">Produk tidak ditemukan.</div>';};search?.addEventListener('input',render);category?.addEventListener('change',render);render();}
 const detail=document.getElementById('detail');if(detail){const id=new URLSearchParams(location.search).get('id');const p=data.find(x=>String(x.id)===String(id));if(!p){detail.innerHTML='<div class="notice">Produk tidak ditemukan.</div>';return;}detail.innerHTML=`<div class="detail-grid"><div class="detail-image">${safeText(p.icon||'📚')}</div><div><span class="tag">${safeText(p.category||'Produk')}</span><h1>${safeText(p.name)}</h1><p>${safeText(p.description||'Produk digital Raufa Digital.')}</p><ul class="check"><li>Produk digital untuk aktivitas belajar</li><li>Tautan produk hanya ditampilkan setelah login member</li><li>Jika belum memiliki produk, dapatkan produk melalui Lynk.id</li></ul><div class="actions">${memberViewButton(p)}<a class="btn btn-outline" href="${safeText(lynkUrl(p))}" target="_blank" rel="noopener noreferrer">Dapatkan di Lynk.id</a><a class="btn btn-light" href="login.html?next=${encodeURIComponent('member-view.html?id='+p.id)}">Login Member</a></div><p class="notice">Akses website memerlukan login. Untuk mencegah tautan file dibagikan ke luar, gunakan file Google Drive dengan akses Terbatas (Restricted), atau penyimpanan privat.</p></div></div>`;}
});
